# Generated by Django 6.0.6 on 2026-07-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('area_of_interest', models.CharField(max_length=120)),
                ('position_applied_for', models.CharField(blank=True, max_length=120)),
                ('experience', models.TextField()),
                ('personal_statement', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='recruitment_cvs/%Y/%m/')),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recruitment application',
                'verbose_name_plural': 'Recruitment applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
